CREATE DATABASE BIKE_STORE;
USE BIKE_STORE;


--10)  Create a temporary table named "#TempOrders" to store order details temporarily.

CREATE TABLE #TempOrders(ORDER_ID INT,CUSTOMER_ID INT,ORDER_STATUS INT, ORDER_DATE DATETIME,REQUIRED_DATE DATETIME,SHIPPED_DATE DATETIME,STORE_ID INT,STAFF_ID INT);


SELECT * FROM ORDERS;