CREATE DATABASE BIKE_STORE;
USE BIKE_STORE;


--11)   Insert a new record into the "customer" table.


INSERT INTO CUSTOMERS VALUES(1446,'ESHA','DESWAL','9967601857','ESHADESWAL@GMAIL.COM','C-1201,GALAXY,KHARGHAR','KHARGHAR','MH',410210);
SELECT * FROM CUSTOMERS;