CREATE DATABASE BIKE_STORE;
USE BIKE_STORE;


--9)  Assign a rank to each product based on their list prices within each category.

SELECT PRODUCT_ID,PRODUCT_NAME,BRAND_ID,CATEGORY_ID,MODEL_YEAR,LIST_PRICE,
DENSE_RANK() OVER (ORDER BY LIST_PRICE DESC)
AS RNK
FROM PRODUCTS;
